-- SQL to create the applications table for the backend
CREATE TABLE IF NOT EXISTS public.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  year TEXT,
  major TEXT,
  gpa NUMERIC(3,2),
  linkedin TEXT,
  why TEXT,
  referral TEXT,
  resume_path TEXT,
  resume_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
